version: "3"
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
volumes:
  dynamodb_data:
