name: Deploy master branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd ./bbapi && npm ci
        working-directory: ./bbapi
      - run: cd ./bbreact && npm ci
      - run: cd ./bbreact && npm run build
        working-directory: ./bbreact
      - name: bbapi deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./bbapi && serverless deploy"
          entrypoint: /bin/sh
      - name: bbreact deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./bbreact && serverless deploy"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
